[pytest]
; allure generate .\allure-results\ -o .\allure-reports\ --clean
addopts = -vs --clean-alluredir --alluredir allure-results
; python_files = test_*.py
; python_files = test_detail.py
python_files = test_list.py
; python_files = test_login.py
; python_files = test_add.py
; python_files = test_getAuthhorinfo.py
; python_files = test_getUserinfo.py



